"""hr_monthly_attendance_ledger_and_payroll_periods

Revision ID: 1e83a3152036
Revises: ed9f7193b825
Create Date: 2026-09-29 16:54:23.561330

"""
"""Adds the monthly attendance ledger (AttendancePeriod) and the payroll
fields needed to gate approval on attendance completeness. Hand-written
rather than autogenerated — see e1ff5060435d's docstring for why
autogenerate against this database re-detects unrelated pre-existing
false-positive index/constraint diffs on every run; those are excluded
here as before.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '1e83a3152036'
down_revision: Union[str, None] = 'ed9f7193b825'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('attendance_imports', sa.Column('period_start', sa.Date(), nullable=True))
    op.add_column('attendance_imports', sa.Column('period_end', sa.Date(), nullable=True))

    op.create_table('hr_attendance_periods',
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('OPEN', 'FINALIZED', name='attendanceperiodstatus'), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finalized_by_id', sa.UUID(), nullable=True),
    sa.Column('override_used', sa.Boolean(), nullable=False, server_default=sa.false()),
    sa.Column('override_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['finalized_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month', 'year', name='uq_attendance_period_month_year'),
    )
    op.create_index(op.f('ix_hr_attendance_periods_status'), 'hr_attendance_periods', ['status'], unique=False)

    # New PayrollStatus.DRAFT value — added outside any DML in this same
    # migration (Postgres 12+ allows ADD VALUE inside a transaction as
    # long as the new value isn't also used within it).
    op.execute("ALTER TYPE payrollstatus ADD VALUE IF NOT EXISTS 'draft'")

    op.add_column('payroll_records', sa.Column('processed_days', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('payroll_records', sa.Column('unprocessed_days', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('payroll_records', sa.Column('other_deductions_rupees', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('payroll_records', sa.Column('is_attendance_complete', sa.Boolean(), nullable=False, server_default=sa.true()))


def downgrade() -> None:
    op.drop_column('payroll_records', 'is_attendance_complete')
    op.drop_column('payroll_records', 'other_deductions_rupees')
    op.drop_column('payroll_records', 'unprocessed_days')
    op.drop_column('payroll_records', 'processed_days')
    # PayrollStatus.DRAFT is intentionally not removed — Postgres cannot
    # drop a single enum value without rebuilding the type, and any 'draft'
    # rows would need to be migrated to another status first.

    op.drop_index(op.f('ix_hr_attendance_periods_status'), table_name='hr_attendance_periods')
    op.drop_table('hr_attendance_periods')

    op.drop_column('attendance_imports', 'period_end')
    op.drop_column('attendance_imports', 'period_start')
